version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout

      - restore_cache:
          keys:
            - toolchain-{{ arch }}

      - restore_cache:
          keys:
            - homebrew-{{ epoch }}
            - homebrew-
            - homebrew

      - run:
          name: Setup Toolchain
          command: |
            if ! [ -x $HOME/.ghcup/bin/ghcup ]; then
              mkdir -p $HOME/.ghcup/bin
              cd $HOME/.ghcup/bin
              curl -LO https://github.com/haskell/ghcup/releases/download/0.0.7/ghcup
              chmod +x $HOME/.ghcup/bin/ghcup
            fi

            export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

            command -v ghc || {
              ghcup install "8.6.3"
              ghcup set "8.6.3"
            }

            command -v cabal || ghcup install-cabal "2.4.1.0"

            command -v stack || {
              curl -sSL https://get.haskellstack.org/ | sh
            }

            stack config set system-ghc --global true
            stack config set install-ghc --global false

            echo 'export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"' >> $BASH_ENV

      - save_cache:
          key: toolchain-{{ arch }}
          paths:
            - "~/.ghcup"
            - /usr/local/bin/stack

      - run:
          name: Homebrew Dependencies
          command: |
            brew bundle
            echo 'export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"' >> $BASH_ENV

      - save_cache:
          key: homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew

      - restore_cache:
          keys:
            - stack-root-v4-{{ arch }}-ghc8.6.3-{{ checksum "snapshot.yaml" }}-{{ checksum "package.yaml" }}
            - stack-root-v4-{{ arch }}-ghc8.6.3-{{ checksum "snapshot.yaml" }}
            - stack-root-v4-{{ arch }}-ghc8.6.3-

      - run:
          name: Build Dependencies
          command: |
            stack build \
              --no-terminal \
              --test \
              --dependencies-only

            # Don’t want this files to be cached. They are large and
            # not needed
            rm -rf ~/.stack/indices/Hackage/00-index.tar*

      - save_cache:
          key: stack-root-v4-{{ arch }}-ghc8.6.3-{{ checksum "snapshot.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "~/.stack"

      - run:
          name: Build
          command: |
            stack build \
              --no-terminal \
              --pedantic

      - run:
          name: Package
          command: |
            set -euxo pipefail

            if [ "$CIRCLE_BRANCH" == "master" && "$CIRCLE_TAG" == v*]; then
              version="$TAG_NAME"
              VERSION=$version TARGET=darwin ./packaging/build-package.sh

              # This is only set when building forked PRs
              if [ -n "$CIRCLE_PR_REPONAME" ]; then
                echo "Skipping uploads for forks"
                exit 0
              fi

              echo "$GCLOUD_SERVICE_KEY" | \
                gcloud auth activate-service-account \
                  circleci-image-uploader@opensourcecoin.iam.gserviceaccount.com \
                  --key-file=-

              ./packaging/upload.sh
            fi
